Neos:
  Neos:
    nodeTypes:
      groups:
        theme:
          position: 150
          label: 'Theme'
          collapsed: false

  Flow:
    mvc:
      routes:
        'Neos.Neos':
          variables:
            'defaultUriSuffix': ''